from __future__ import annotations
from collections import defaultdict

EMBEDDING_MODEL = "paraphrase-multilingual-MiniLM-L12-v2"
_embedding_model = None


def _get_embedding_model():
    global _embedding_model
    if _embedding_model is None:
        from sentence_transformers import SentenceTransformer
        _embedding_model = SentenceTransformer(EMBEDDING_MODEL)
    return _embedding_model


def run_topic_modeling(texts: list[str], min_topic_size: int = 10) -> dict:
    from bertopic import BERTopic
    embedding_model = _get_embedding_model()
    adjusted_min = max(3, min(min_topic_size, len(texts) // 10))

    topic_model = BERTopic(embedding_model=embedding_model, min_topic_size=adjusted_min,
                            calculate_probabilities=False, verbose=False)
    safe_texts = [t if t and t.strip() else "." for t in texts]
    topics, _ = topic_model.fit_transform(safe_texts)

    result_topics = []
    for _, row in topic_model.get_topic_info().iterrows():
        tid = int(row["Topic"])
        if tid == -1: continue
        words_weights = topic_model.get_topic(tid) or []
        keywords = [word for word, _ in words_weights[:10]]
        label = " | ".join(keywords[:3]) if keywords else f"Topic {tid}"
        result_topics.append({"topic_id": tid, "label": label, "keywords": keywords, "count": int(row["Count"])})

    return {"topic_assignments": [int(t) for t in topics], "topics": result_topics}


def aggregate_topic_sentiments(topic_assignments: list[int], sentiment_labels: list[str]) -> dict[int, dict]:
    VALID = {"positive", "neutral", "negative"}
    summary: dict = defaultdict(lambda: {"positive": 0, "neutral": 0, "negative": 0, "count": 0})
    for tid, label in zip(topic_assignments, sentiment_labels):
        if tid == -1: continue
        summary[tid]["count"] += 1
        summary[tid][label if label in VALID else "neutral"] += 1
    return dict(summary)


# ── LLM-generated topic labels ────────────────────────────────────────────────
# Replaces raw keyword-join labels (e.g. "song | music | voice") with a short,
# readable phrase (e.g. "Praise for the Song's Vocals") generated by the same
# local Ollama instance used for RAG chat. Falls back to the keyword-join
# label on any failure (Ollama not running, timeout, model not pulled) so a
# missing LLM never blocks the pipeline.

import os

OLLAMA_HOST  = os.getenv("OLLAMA_HOST",  "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2")
_LLM_TIMEOUT = 15   # seconds — short, since this runs once per topic (≤8 topics) inline in the pipeline


def _generate_label(keywords: list[str]) -> str | None:
    """Ask Ollama for a short natural-language label from a topic's keywords.
    Returns None on any failure so the caller can fall back to keyword-join."""
    import requests

    prompt = (
        f"Keywords from a cluster of YouTube comments: {', '.join(keywords[:8])}.\n"
        f"Reply with ONLY a short, natural 2-4 word topic label describing what "
        f"these comments are about. No quotes, no punctuation, no explanation."
    )
    try:
        resp = requests.post(
            f"{OLLAMA_HOST}/api/generate",
            json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
            timeout=_LLM_TIMEOUT,
        )
        resp.raise_for_status()
        text = resp.json().get("response", "").strip()
        # Strip stray quotes/punctuation the model sometimes adds anyway
        text = text.strip('"\'.,!?').strip()
        # Guard against empty or absurdly long replies (model going off-script)
        if 0 < len(text) <= 60:
            return text
        return None
    except Exception:
        return None


def label_topics_with_llm(topics: list[dict]) -> list[dict]:
    """
    Given the topics list from run_topic_modeling() (each with a "keywords"
    list and a keyword-join "label"), try to replace each label with an
    LLM-generated phrase. Topics where generation fails keep their original
    keyword-join label untouched — this function never raises.
    """
    for topic in topics:
        keywords = topic.get("keywords") or []
        if not keywords:
            continue
        llm_label = _generate_label(keywords)
        if llm_label:
            topic["label"] = llm_label
        # else: keep the existing keyword-join label as-is
    return topics
